language: objective-c
osx_image: xcode7.2
xcode_project: OSLibrary.xcodeproj
xcode_scheme: OSLibrary
script:
  - xctool -project OSLibrary.xcodeproj -scheme OSLibrary build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)